from pathlib import Path
import json
p=Path('src/data/market-prices.json');d=json.loads(p.read_text(encoding='utf-8'))
r=d['catalog']['rev-pack-apple-plastic'];r.update(referencePriceTL=0.405,referenceSource='https://www.ozalpambalaj.com.tr/rulo-manav-seffaf-poset-kucuk-boy-7-kg',referenceProduct='Naksan Arma küçük boy manav poşeti, 4000 adet / 1620 TL',referenceSpecification='21x42 cm, 14 cm körük; 20 rulo x 200 adet',note='PRICE REVIEW REQUIRED: toptan koli referansı bulundu; oyun görseli ve adet maliyeti eşleştirmesi tamamlanmadı.')
p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
lines=['# Ekonomi, yatırım ve aydınlatma revizyonu — 6 Ekim 2026','', '## Uygulanan davranış','', '- Dönemler arasında kalan para korunur. Yeni dönem tasarrufunun %25’i, en fazla ₺500, yalnız bir kez kasaya eklenir.', '- Yeni karar sürümünde 4. döneme geçişte ₺7.500 satış geliri bir kez eklenir. Açıklama oyuncu onaylayana kadar kalır.', '- 550 W panel ₺8.475, yalnız son dönemde ve puansız isteğe bağlıdır. ₺8.400 kasada ₺75 eksik gösterilir. Kurulum ve ek ekipman panel fiyatına dahil değildir.', '- Mevcut akkor ampul satın alınmaz; mevcutla devam et seçeneği ₺0’dır. E27 9 W LED ₺50, halojen ₺175. Para ile karar puanı bağımsızdır.', '- LED şerit ayrı isteğe bağlı destek aydınlatmasıdır. Sahne yerleşimi ve sıcak ışık etkisi hazırdır; görselin 3 m fişli/anahtarlı set olduğu doğrulanmadığı için satın alma kapalıdır.', '- Sonuç ekranında kalan para, toplam harcama ve tahmini dönem tasarrufu ayrıdır.', '- Kayıtlarda gerçek satın alma maliyeti saklanır. Eski kayıtların parası ve önceki harcamaları yeni katalogla yeniden hesaplanmaz. Mevcut ampulle devam edilmiş eski kayıtlar kabul edilir.', '', '## Fiyat kaynakları ve sınırlar','', 'Aşağıdaki tarihler araştırmanın kontrol tarihidir. Arama indeksleri ve mağaza sayfaları gecikmeli olabilir; bütün fiyatların Ekim 2026 boyunca canlı stok/fiyat garantisi olduğu iddia edilmez. verified, verilen kullanıcı referansı veya gözlenen satıcı referansı bulunduğunu belirtir. Kaynaklar oyuncu arayüzünde gösterilmez. Gider ve tasarruflar oyun senaryosudur; satıcının ürününe ait doğrulanmış tasarruf vaadi değildir.', '', 'Eski sürüm fiyatları yalnız kayıt uyumluluğu için historicalLegacyPrices altında korunur. Yeni oyun bu tarihsel fiyatları kullanmaz.', '', '| Ürün | Oyun fiyatı | Durum | Kaynak / kapsam |','|---|---:|---|---|']
for r in d['catalog'].values():
 price='—' if r['priceTL'] is None else str(r['priceTL'])+' TL'
 src=r['referenceSource'] or ('Kullanıcı brifi' if r.get('provenance')=='user_brief' else 'Mevcut eşya / teyit gerekli')
 lines.append(f"| {r['displayName']} (`{r['id']}`) | {price} | {r['priceStatus']} | {src} — {r.get('referenceSpecification','')} {r.get('note','')} |")
lines+=['','## PRICE REVIEW REQUIRED','']
for r in d['catalog'].values():
 if r['priceStatus']=='needs_review':lines.append('- '+r['displayName']+' (`'+r['id']+'`): '+r['note'])
lines+=['','İncelenen ama kapsamı eşleşmeyen ürünlere tahmini fiyat girilmedi. İnceleme bekleyen seçenekler görünür; yanlış kesin fiyatla satın alınamaz. Diğer doğrulanmış seçeneklerle oyun tamamlanabilir.','']
Path('EKONOMI-REVIZYON-RAPORU.md').write_text('\n'.join(lines),encoding='utf-8')
for file in ['DESIGN.md','UX-CONTRACT.md']:
 with Path(file).open('a',encoding='utf-8') as f:f.write('\n\n## 6 Ekim 2026 ekonomi revizyonu\nMerkezi fiyat kataloğu src/data/market-prices.json. Fiyat, karar puanından bağımsızdır. Dönem katkısı yeni tasarrufun %25’i, tavan ₺500; son dönem satış geliri bir defa ₺7.500. Gelir ekranı onaysız kapanmaz. Eksik fiyat satın almayı engeller, bilinmeyen bedel sıfır gibi gösterilmez. Mevcut akkor ampul ürün rafında satılmaz. LED şerit ayrı ve puansız destek aydınlatmasıdır. Ayrıntılar EKONOMI-REVIZYON-RAPORU.md.\n')
