from pathlib import Path
import json
p=Path('src/navigation.ts');s=p.read_text(encoding='utf-8').replace('nextOpportunity, zoneFor','nextOpportunity, zoneFor, opportunityFor, opportunities');s=s.replace('if(s.decisionVersion===1) {const o=nextOpportunity(s,room);','if(s.decisionVersion===1) {const lesson=s.lessons?.find(l=>!l.acknowledged&&!l.remind); const pending=lesson&&(opportunityFor(lesson.id)||opportunities.find(o=>`sort-${o.id}`===lesson.id)); const o=pending?.roomId===room?pending:nextOpportunity(s,room);');p.write_text(s,encoding='utf-8')
p=Path('src/main.ts');s=p.read_text(encoding='utf-8');s=s.replace('btn(z.problem, `zone:${z.id}`','btn(s.decisionVersion===1 ? z.name : z.problem, `zone:${z.id}`');s=s.replace('Önce tasarruf, sonra skor','Toplam karar puanına göre sıralanır');s=s.replace('<strong>%${fmt(r.savingPercent)}</strong><p>tasarruf · ${fmt(r.score)} puan</p>','<strong>${fmt(r.score)}</strong><p>toplam puan</p>');s=s.replace('<strong>%${fmt(r.savingPercent)}</strong><span>${fmt(r.score)}</span>','<strong>${fmt(r.score)} puan</strong>');s=s.replace('Bu cihazdaki resmî sonuçlar · Toplam karar puanına göre sıralanır</p>','Bu cihazdaki resmî sonuçlar · Toplam karar puanına göre sıralanır</p><p class="subtle">Eski sürüm sonuçları yönetim ve yedekte korunur; farklı puan kuralları birlikte karşılaştırılmaz.</p>');s=s.replace('Bu dönem gider yükseldi. Seçiminizi sonradan değiştirebilirsiniz.','Bu dönem gider yükseldi. Sonraki kararında ürünün işlevine de bak.');s=s.replace('<p class="sort-instruction">','<p class="subtle">İlk eşleştirme puana sayılır; sonra yeniden deneyebilirsin.</p><p class="sort-instruction">');s=s.replace('<div class="sorting-items">','<div class="sorting-items" style="--columns:${o.items!.length}">');s=s.replace('<div class="sorting-targets">','<div class="sorting-targets" style="--columns:${o.targets!.length}">')
s=s.replace('case "decision": openDecision(arg); break;','''case "decision": openDecision(arg); break;
    case "load-select": selectedLoad=arg;openDecision('laundry-load');break;''');s=s.replace("let selectedSortItem = '', activeSort = '';","let selectedSortItem = '', activeSort = '', selectedLoad = '';")
s=s.replace("`choose:${id}`,'decision-option'","`${o.kind==='load'?'load-select':'choose'}:${id}`,`decision-option ${selectedLoad===id?'selected':''}`")
s=s.replace("</div>${btn('Bir daha bak','close','ghost')}`);","</div>${o.kind==='load'?btn('BU YÜKLE ÇALIŞTIR',`choose:${selectedLoad}`,'primary',o.choices.includes(selectedLoad)?'':'disabled'):''}${btn('Bir daha bak','close','ghost')}`);")
s=s.replace('<div class="final-score">Yarışma skoru <b>${fmt(score(s))}</b></div>','<div class="final-score">TOPLAM SKOR <b>${fmt(score(s))}${s.decisionVersion===1?" / 1.800":""}</b></div>');p.write_text(s,encoding='utf-8')
p=Path('src/model.ts');s=p.read_text(encoding='utf-8').replace('(a.rulesVersion===1 && b.rulesVersion===1 ?','((b.rulesVersion??0)-(a.rulesVersion??0)) || (a.rulesVersion===1 && b.rulesVersion===1 ?');s=s.replace('  if(s.decisionVersion===1) assertChoice(s,id);','  if(s.decisionVersion===1) {assertChoice(s,id);if(s.inventory.length)throw Error("Önce hazır ürününü yerleştir.");}');s=s.replace('        "Tarih",','        "Tarih",\n        "Puan kuralı",');s=s.replace('        r.completedAt,','        r.completedAt,\n        r.rulesVersion===1?"Karar puanı v1":"Eski ekonomi puanı",');p.write_text(s,encoding='utf-8')
p=Path('src/decisions/copy.json');d=json.loads(p.read_text(encoding='utf-8-sig'));d['rev-tap-repair']['resultText']='Conta yenilendiği için kaçak kesildi. Evde damlayan musluğu da küçük bir bakımla onarabilirsin.'
for id in ['rev-hygiene-paper','rev-hygiene-other','rev-hygiene-organic']:d[id]['resultText']='Kirli peçete ve ıslak mendil diğer atıktır. Temiz karton rulo ise kâğıt kutusuna gider.'
p.write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf-8')
